/*
 * This file is part of the mrnf-foresttools library
 *
 * Copyright (C) 2016 Mathieu Fortin - LERFoB AgroParisTech/INRA
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package quebecmrnfutility.biosim;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

@Deprecated
public class ClimateVariables implements Serializable {

	public static enum Variable {
		MeanAnnualTempC,
		MeanAnnualPrecMm;
	}

	private final Map<Variable, Double> variableMap;
	private final String plotID;
	
	public ClimateVariables(String plotID) {
		this.plotID = plotID;
		variableMap = new HashMap<Variable, Double>();
	}

	/**
	 * This method returns a climate variable generated by BioSim.
	 * @param enumVar the variable
	 * @return its value, a Double instance if it exists or NaN if it does not 
	 */
	public Double getVariable(Variable enumVar) {
		Double value = variableMap.get(enumVar);
		if (value == null) {
			value = Double.NaN;
		}
		return value;
	}
	
	public void setVariable(Variable enumVar, double value) {
		variableMap.put(enumVar, value);
	}
	
	public String getPlotId() {return plotID;}
	
	@Override
	public String toString() {
		return "Plot: " + plotID + "; " 
				+ Variable.MeanAnnualTempC.name() + " = " + getVariable(Variable.MeanAnnualTempC) + "; "
				+ Variable.MeanAnnualPrecMm.name() + " = " + getVariable(Variable.MeanAnnualPrecMm);
	}
}
